/* Generated By:JJTree: Do not edit this line. ASTforStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTforStatement extends SimpleNode {
  public ASTforStatement(int id) {
    super(id);
  }

  public ASTforStatement(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=788e1b0c07846ef7f5733e48bc11ffe2 (do not edit this line) */
