/* Generated By:JJTree: Do not edit this line. ASTfieldDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfieldDecl extends SimpleNode {
  public ASTfieldDecl(int id) {
    super(id);
  }

  public ASTfieldDecl(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5d2e1f7e7572da9589f00e8eff46ae86 (do not edit this line) */
