/* Generated By:JJTree: Do not edit this line. ASTintLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTintLiteral extends SimpleNode {
  public ASTintLiteral(int id) {
    super(id);
  }

  public ASTintLiteral(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d29b4cba866857ec9bfdd08f7d006210 (do not edit this line) */
