/* Generated By:JJTree: Do not edit this line. ASTmethodDeclVar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmethodDeclVar extends SimpleNode {
  public ASTmethodDeclVar(int id) {
    super(id);
  }

  public ASTmethodDeclVar(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=53fe92b3262f367e45d4c665f0c7610d (do not edit this line) */
