/* Generated By:JJTree: Do not edit this line. ASTvarDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvarDecl extends SimpleNode {
  public ASTvarDecl(int id) {
    super(id);
  }

  public ASTvarDecl(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a2e39b3f76e542ff7db0020dcf1b229 (do not edit this line) */
