/* Generated By:JJTree: Do not edit this line. CuteintLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteintLiteral extends SimpleNode {
  public CuteintLiteral(int id) {
    super(id);
  }

  public CuteintLiteral(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2bced74292b5e6d71dd2880406f9c2e0 (do not edit this line) */
