/* Generated By:JJTree: Do not edit this line. Cuteprogram.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Cuteprogram extends SimpleNode {
  public Cuteprogram(int id) {
    super(id);
  }

  public Cuteprogram(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2dede63a321f5d2b9e2aaf6d38a44c85 (do not edit this line) */
