/* Generated By:JJTree: Do not edit this line. CutemethodDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CutemethodDecl extends SimpleNode {
  public CutemethodDecl(int id) {
    super(id);
  }

  public CutemethodDecl(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a7ca23839950ce768b4692041ab9c382 (do not edit this line) */
