/* Generated By:JJTree: Do not edit this line. Cuteexpression1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Cuteexpression1 extends SimpleNode {
  public Cuteexpression1(int id) {
    super(id);
  }

  public Cuteexpression1(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=04e656e552142e8f4b8f63ec7148cc1d (do not edit this line) */
