/* Generated By:JJTree: Do not edit this line. CutemethodDeclVar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CutemethodDeclVar extends SimpleNode {
  public CutemethodDeclVar(int id) {
    super(id);
  }

  public CutemethodDeclVar(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=11454e776f64a841bd705f91718db926 (do not edit this line) */
