/* Generated By:JJTree: Do not edit this line. CutecalloutArg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CutecalloutArg extends SimpleNode {
  public CutecalloutArg(int id) {
    super(id);
  }

  public CutecalloutArg(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=20742e10be7935edf15e38f96a87331a (do not edit this line) */
