/* Generated By:JJTree: Do not edit this line. CutevarDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CutevarDecl extends SimpleNode {
  public CutevarDecl(int id) {
    super(id);
  }

  public CutevarDecl(DecafParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f9fac977628e9d4dc0e140f11d927f1 (do not edit this line) */
