/* Generated By:JavaCC: Do not edit this line. DecafParserVisitor.java Version 5.0 */
public interface DecafParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Cuteprogram node, Object data);
  public Object visit(CutefieldDeclVar node, Object data);
  public Object visit(CutefieldDecl node, Object data);
  public Object visit(CutemethodDeclVar node, Object data);
  public Object visit(CutemethodDecl node, Object data);
  public Object visit(Cuteblock node, Object data);
  public Object visit(CutevarDecl node, Object data);
  public Object visit(Cutetype node, Object data);
  public Object visit(CuteifStatement node, Object data);
  public Object visit(CuteforStatement node, Object data);
  public Object visit(Cutestatement node, Object data);
  public Object visit(Cuteassignment node, Object data);
  public Object visit(Cutelocation node, Object data);
  public Object visit(CutemethodCall node, Object data);
  public Object visit(CutemethodName node, Object data);
  public Object visit(Cuteexpression node, Object data);
  public Object visit(Cuteexpression1 node, Object data);
  public Object visit(CutecalloutArg node, Object data);
  public Object visit(Cuteliteral node, Object data);
  public Object visit(CuteintLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=2c903e0cf6c66813e8f5cba336ffdc95 (do not edit this line) */
