/* Generated By:JavaCC: Do not edit this line. DecafParserTreeConstants.java Version 5.0 */
public interface DecafParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFIELDDECLVAR = 1;
  public int JJTFIELDDECL = 2;
  public int JJTMETHODDECLVAR = 3;
  public int JJTMETHODDECL = 4;
  public int JJTBLOCK = 5;
  public int JJTVARDECL = 6;
  public int JJTTYPE = 7;
  public int JJTIFSTATEMENT = 8;
  public int JJTFORSTATEMENT = 9;
  public int JJTSTATEMENT = 10;
  public int JJTASSIGNMENT = 11;
  public int JJTLOCATION = 12;
  public int JJTMETHODCALL = 13;
  public int JJTMETHODNAME = 14;
  public int JJTEXPRESSION = 15;
  public int JJTEXPRESSION1 = 16;
  public int JJTCALLOUTARG = 17;
  public int JJTLITERAL = 18;
  public int JJTINTLITERAL = 19;


  public String[] jjtNodeName = {
    "program",
    "fieldDeclVar",
    "fieldDecl",
    "methodDeclVar",
    "methodDecl",
    "block",
    "varDecl",
    "type",
    "ifStatement",
    "forStatement",
    "statement",
    "assignment",
    "location",
    "methodCall",
    "methodName",
    "expression",
    "expression1",
    "calloutArg",
    "literal",
    "intLiteral",
  };
}
/* JavaCC - OriginalChecksum=92c38b5a78faeb43aa4419f5ebeb7a39 (do not edit this line) */
