/* Generated By:JJTree: Do not edit this line. CuteType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteType extends SimpleNode {

  UglySymbolType type;
	
  public CuteType(int id) {
    super(id);
  }

  public CuteType(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
  
  @Override
  public String toString() {
	  return String.format("%s: %s", super.toString(), this.type.toString());
  }
  
}
/* JavaCC - OriginalChecksum=119549f3806fa288da2a548d329ba793 (do not edit this line) */
