/* Generated By:JJTree: Do not edit this line. CuteDisjunctionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteDisjunctionExpression extends CuteExpression {
  public CuteDisjunctionExpression(int id) {
    super(id);
  }

  public CuteDisjunctionExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=83520949d733c1b81212fda2364c157c (do not edit this line) */
