/* Generated By:JJTree: Do not edit this line. CuteCalloutArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteCalloutArgument extends SimpleNode {
  public CuteCalloutArgument(int id) {
    super(id);
  }

  public CuteCalloutArgument(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7822d41499637a3cd36a2486d762581d (do not edit this line) */
