/* Generated By:JJTree: Do not edit this line. CuteMethodName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteMethodName extends SimpleNode {

  String name;

  public CuteMethodName(int id) {
    super(id);
  }

  public CuteMethodName(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=65044b444f51d72cd361ea5ad6c6c949 (do not edit this line) */
