/* Generated By:JJTree: Do not edit this line. CuteAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class CuteAssignment extends SimpleNode {


  /** Could've used value to store the friggin' operator */
  boolean isShortcut;

  public CuteAssignment(int id) {
    super(id);
  }

  public CuteAssignment(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=03d17056793ca01537d8aa6cfaf00414 (do not edit this line) */
