/* Generated By:JJTree: Do not edit this line. CuteCharLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteCharLiteral extends CuteLiteral {

  public CuteCharLiteral(int id) {
    super(id);
  }

  public CuteCharLiteral(Decaf p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=6f438aa1e7a2c380e0b2ad3508811f03 (do not edit this line) */
