/* Generated By:JJTree: Do not edit this line. CuteRelationExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteRelationExpression extends CuteExpression {
  public CuteRelationExpression(int id) {
    super(id);
  }

  public CuteRelationExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ad55c10e1db298e4e5910741c56fed9 (do not edit this line) */
