/* Generated By:JJTree: Do not edit this line. CuteIntLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteIntLiteral extends CuteLiteral {

  int base;
  
  public CuteIntLiteral(int id) {
    super(id);
  }

  public CuteIntLiteral(Decaf p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
  
}
/* JavaCC - OriginalChecksum=7c590928bfa739716cb67ed5bc52bee0 (do not edit this line) */
