/* Generated By:JJTree: Do not edit this line. CuteEqualityExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteEqualityExpression extends CuteExpression {
  public CuteEqualityExpression(int id) {
    super(id);
  }

  public CuteEqualityExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c768058ab3bf93430ecfdfb9122832c9 (do not edit this line) */
