/* Generated By:JJTree: Do not edit this line. CuteBooleanLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteBooleanLiteral extends CuteLiteral {

  public CuteBooleanLiteral(int id) {
    super(id);
  }

  public CuteBooleanLiteral(Decaf p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=7951cc45b6c757daed97b45537f9e7e5 (do not edit this line) */
