/* Generated By:JJTree: Do not edit this line. CuteFactorExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteFactorExpression extends CuteExpression {
  public CuteFactorExpression(int id) {
    super(id);
  }

  public CuteFactorExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=478e05fdd8e77ef70ed32a49352618c0 (do not edit this line) */
