/* Generated By:JJTree: Do not edit this line. CuteStringLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteStringLiteral extends SimpleNode {
  public CuteStringLiteral(int id) {
    super(id);
  }

  public CuteStringLiteral(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a15f2e72f44eb86d6bbf49928e5526b5 (do not edit this line) */
