/* Generated By:JJTree: Do not edit this line. CuteFieldDeclarationUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteFieldDeclarationUnit extends SimpleNode {
  
  String name;
  int size;
  boolean isArray;
	
  public CuteFieldDeclarationUnit(int id) {
    super(id);
  }

  public CuteFieldDeclarationUnit(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
  
  @Override
  public String toString() {
	if (size == -1) {
		return String.format("%s: %s", super.toString(), this.name);
	} else {
		return String.format("%s: %s[%d]", super.toString(), this.name, this.size);
	}
  }
  
}
/* JavaCC - OriginalChecksum=5638b30c93651afa0229596066c5d78c (do not edit this line) */
