/* Generated By:JJTree: Do not edit this line. CuteCalloutStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteCalloutStatement extends SimpleNode {
  public CuteCalloutStatement(int id) {
    super(id);
  }

  public CuteCalloutStatement(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=511f816fbbfc34eda075d073073302bc (do not edit this line) */
