/* Generated By:JJTree: Do not edit this line. CuteBreakStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteBreakStatement extends SimpleNode {
  public CuteBreakStatement(int id) {
    super(id);
  }

  public CuteBreakStatement(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed95f2a1ae0413717efd13688d34d9b0 (do not edit this line) */
