/* Generated By:JJTree: Do not edit this line. CuteExpressionUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class CuteExpressionUnit extends CuteExpression {

  public CuteExpressionUnit(int id) {
    super(id);
  }

  public CuteExpressionUnit(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9318e29c672b0d6986ac48f434adf178 (do not edit this line) */
