/* Generated By:JJTree: Do not edit this line. CuteMethodDeclarationParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteMethodDeclarationParameter extends SimpleNode {
	
  UglySymbolType type;
  String name;
	
  public CuteMethodDeclarationParameter(int id) {
    super(id);
  }

  public CuteMethodDeclarationParameter(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
  
  @Override
  public String toString() {
	  return String.format("%s: %s %s", super.toString(), this.type, this.name);
  }
  
}
/* JavaCC - OriginalChecksum=70842824f1379d06920174252acc824a (do not edit this line) */
