/* Generated By:JJTree: Do not edit this line. CuteLocation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteLocation extends SimpleNode {

  String name;
  boolean isArrayAccess;
  /**
   * To be used only when visiting.
   */
  UglySymbol entry;

  public CuteLocation(int id) {
    super(id);
  }

  public CuteLocation(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=53e2590875ee36a7096d8c1969445f84 (do not edit this line) */
