/* Generated By:JJTree: Do not edit this line. CuteConjunctionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteConjunctionExpression extends CuteExpression {
  public CuteConjunctionExpression(int id) {
    super(id);
  }

  public CuteConjunctionExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=61dbb2d7a07e7c869c878aff0e4d93b2 (do not edit this line) */
