import java.util.ArrayList;
import java.util.List;

/* Generated By:JJTree: Do not edit this line. CuteFieldDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteFieldDeclaration extends SimpleNode {
	
  UglySymbolType type;
  /**
   * name, isArray, size
   */
  List<UglyTriplet<String, Boolean, Integer>> infos;
	
  public CuteFieldDeclaration(int id) {
    super(id);
    this.infos = new ArrayList<UglyTriplet<String, Boolean, Integer>>();
  }

  public CuteFieldDeclaration(Decaf p, int id) {
    super(p, id);
    this.infos = new ArrayList<UglyTriplet<String, Boolean, Integer>>();
  }

  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
  
  @Override
  public String toString() {
	  StringBuilder builder = new StringBuilder(super.toString());
	  builder.append(": ");
	  builder.append(type.toString());
	  builder.append(": ");
	  if (this.infos == null || this.infos.isEmpty()) {
		  System.err.println("Empty field declaration.");
		  builder.append("Empty");
      return builder.toString();
	  }
    builder.append("[");
	  for (UglyTriplet<String, Boolean, Integer> infos : this.infos) {
      builder.append(infos.v);
      if (infos.w) {
        builder.append("[");
        builder.append(infos.x);
        builder.append("]");
      }
      builder.append(", ");
	  }
    builder.delete(builder.length() - 2, builder.length());
    builder.append("]");
	  return builder.toString();
  }
  
}
/* JavaCC - OriginalChecksum=d61457b45e744e22f38303f4f29da40f (do not edit this line) */
