/* Generated By:JJTree: Do not edit this line. CuteBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class CuteBlock extends SimpleNode {

  boolean shouldPushScope;
  String name;

  public CuteBlock(int id) {
    super(id);
    this.shouldPushScope = true;
  }

  public CuteBlock(Decaf p, int id) {
    super(p, id);
    this.shouldPushScope = true;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder(super.toString());
    if (this.name != null) {
      builder.append(": ");
      builder.append(this.name);
    }
    if (this.shouldPushScope) {
      builder.append(" (new scope)");
    } else {
      builder.append(" (no new scope)");
    }
    return builder.toString();
  }

  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=8481bfc9c6ce052861a1fcf9e1d2dfe5 (do not edit this line) */
