import java.util.List;
import java.util.LinkedList;

/* Generated By:JJTree: Do not edit this line. CuteExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteExpression extends SimpleNode {

  UglySymbolType type;

  /**
   * Representation of the operator between this expression and the one before.
   */
  String operator;

  public CuteExpression(int id) {
    super(id);
  }

  public CuteExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7b5d48b0ebef3cb8e2134028defdf5b6 (do not edit this line) */
