/* Generated By:JJTree: Do not edit this line. CuteCuteCalloutStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteCuteCalloutStatement extends SimpleNode {
  public CuteCuteCalloutStatement(int id) {
    super(id);
  }

  public CuteCuteCalloutStatement(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e233c4a04359919f1b96a8cd7a89ffb7 (do not edit this line) */
