/* Generated By:JJTree: Do not edit this line. CuteUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class CuteUnaryExpression extends CuteExpression {

  Boolean isArithmetic;

  public CuteUnaryExpression(int id) {
    super(id);
  }

  public CuteUnaryExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c193f53951ad068cd715b59ac80d3b6 (do not edit this line) */
