import java.util.List;
import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. CuteIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class CuteIfStatement extends SimpleNode {

  int elseLine;
  int elseColumn;
  UglyLabel elseLabel;
  UglyLabel endIfLabel;

  List<UglyInstruction> middleInstructions;

  public CuteIfStatement(int id) {
    super(id);
    this.middleInstructions = new ArrayList<UglyInstruction>();
  }

  public CuteIfStatement(Decaf p, int id) {
    super(p, id);
    this.middleInstructions = new ArrayList<UglyInstruction>();
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1996ce930398a441b4ad5b12b019d50c (do not edit this line) */
