/* Generated By:JJTree: Do not edit this line. CuteTermExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Cute,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CuteTermExpression extends CuteExpression {
  public CuteTermExpression(int id) {
    super(id);
  }

  public CuteTermExpression(Decaf p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DecafVisitor visitor, UglySymbolTable data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=70e8e4aebcd4d3bf539f673e27b6fa15 (do not edit this line) */
