/* Generated By:JavaCC: Do not edit this line. DecafTreeConstants.java Version 5.0 */
public interface DecafTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFIELDDECLARATIONUNIT = 1;
  public int JJTFIELDDECLARATION = 2;
  public int JJTMETHODDECLARATIONPARAMETER = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTBLOCK = 5;
  public int JJTVARIABLEDECLARATION = 6;
  public int JJTTYPE = 7;
  public int JJTIFSTATEMENT = 8;
  public int JJTFORSTATEMENT = 9;
  public int JJTRETURNSTATEMENT = 10;
  public int JJTBREAKSTATEMENT = 11;
  public int JJTCONTINUESTATEMENT = 12;
  public int JJTSTATEMENT = 13;
  public int JJTASSIGNMENT = 14;
  public int JJTLOCATION = 15;
  public int JJTMETHODCALL = 16;
  public int JJTCALLOUTSTATEMENT = 17;
  public int JJTMETHODNAME = 18;
  public int JJTEXPRESSION = 19;
  public int JJTDISJUNCTIONEXPRESSION = 20;
  public int JJTCONJUNCTIONEXPRESSION = 21;
  public int JJTEQUALITYEXPRESSION = 22;
  public int JJTRELATIONEXPRESSION = 23;
  public int JJTTERMEXPRESSION = 24;
  public int JJTFACTOREXPRESSION = 25;
  public int JJTUNARYEXPRESSION = 26;
  public int JJTEXPRESSIONUNIT = 27;
  public int JJTCALLOUTARGUMENT = 28;
  public int JJTLITERAL = 29;
  public int JJTCHARLITERAL = 30;
  public int JJTINTLITERAL = 31;
  public int JJTBOOLEANLITERAL = 32;
  public int JJTSTRINGLITERAL = 33;


  public String[] jjtNodeName = {
    "Program",
    "FieldDeclarationUnit",
    "FieldDeclaration",
    "MethodDeclarationParameter",
    "MethodDeclaration",
    "Block",
    "VariableDeclaration",
    "Type",
    "IfStatement",
    "ForStatement",
    "ReturnStatement",
    "BreakStatement",
    "ContinueStatement",
    "Statement",
    "Assignment",
    "Location",
    "MethodCall",
    "CalloutStatement",
    "MethodName",
    "Expression",
    "DisjunctionExpression",
    "ConjunctionExpression",
    "EqualityExpression",
    "RelationExpression",
    "TermExpression",
    "FactorExpression",
    "UnaryExpression",
    "ExpressionUnit",
    "CalloutArgument",
    "Literal",
    "CharLiteral",
    "IntLiteral",
    "BooleanLiteral",
    "StringLiteral",
  };
}
/* JavaCC - OriginalChecksum=0c00666e9faacf899a27200635b2b7f5 (do not edit this line) */
